# Generated by Django 4.1.6 on 2023-02-01 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_info_address_remove_info_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='GPA',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
